### ISSUE TITLE
[Bug] Flower textures are squished when only one singular flower is present

### ISSUE THREAD

**Issue by lxly9** [ItsMaddieNow/Building-Tweaks#1]
When only a singular flower is present, they become very small when placed/generated and their textures are slightly squished down
![image](https://github.com/ItsMaddieNow/Building-Tweaks/assets/102386118/ffb1dd42-eb99-4c21-8c6a-c371d58f20a2)
normal poppy size for reference
![image](https://github.com/ItsMaddieNow/Building-Tweaks/assets/102386118/f69dfe85-047a-49b2-8556-c4b8c43c2888)

Im using the latest version of maddies building tweaks and 0.8.0 of ARRP.

**Comment by lxly9** [comment]
lmao i accidentally pasted the same image twice

**Comment by lxly9** [comment]
![2023-10-18_21 16 34](https://github.com/ItsMaddieNow/Building-Tweaks/assets/102386118/8b8015ea-0dbf-4929-9494-52e103c925f1)
this should be the right one lolol

**Comment by ItsMaddieNow** [comment]
is this along the lines of what you're expecting? 
![2023-10-19_19 33 44](https://github.com/ItsMaddieNow/Building-Tweaks/assets/36354501/72494063-f5db-4d87-a078-ee3216c6c63e)

**Comment by lxly9** [comment]
yes, exactly! i think it behaved that way before the rewrite afaik

**Comment by lxly9** [comment]
also sidenote this is one of my fav mods tbh :)

**Comment by ItsMaddieNow** [comment]
Aww, thanks that means alot.
<3
